# Generated by Django 3.0.1 on 2020-01-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswers',
            old_name='question',
            new_name='questionId',
        ),
    ]
