# Generated by Django 3.0.1 on 2019-12-27 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classEnrolled',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classUnderTaken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
    ]
