# Generated by Django 3.0.1 on 2019-12-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191227_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classEnrolled',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classUnderTaken',
        ),
    ]
