# Generated by Django 3.0.1 on 2020-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignmentQuestion',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='description',
            field=models.CharField(max_length=75, null=True, verbose_name='Description'),
        ),
    ]
