# Generated by Django 3.0.1 on 2020-01-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200103_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='assignmentQuestion',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
