# Generated by Django 3.0.1 on 2020-01-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_notes_assignmentquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='assignmentQuestion',
            new_name='notesFile',
        ),
    ]
