# Generated by Django 3.0.1 on 2020-01-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191227_1745'),
        ('classroom', '0005_auto_20200104_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionFile', models.FileField(upload_to='uploads/')),
                ('assignmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Assignments')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
