# Generated by Django 3.0.1 on 2020-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_studentassignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
