# Generated by Django 3.0.1 on 2020-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200110_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='maximumMarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
