# Generated by Django 3.0.1 on 2020-01-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200110_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
