# Generated by Django 3.0.1 on 2020-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20200110_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='marks',
            field=models.PositiveIntegerField(),
        ),
    ]
